import '../globals.css'
import type { Metadata } from 'next'
import { Mukta, Marcellus } from 'next/font/google'

const mukta = Marcellus({ weight: ['400'], subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={mukta.className}>{children}</body>
    </html>
  )
}
